### PR TITLE
update to support new vtk-m

### PR DESCRIPTION
**Pull request by cyrush**
api changes for new vtk-m

majority of work done by jameskress

### CODE REVIEW

**Comment by jameskress** [comment]
@cyrush Let me know if you see any issues with this RC of vtkm and I can help work out any issues. Once this is in I will get the versions of VTKm and VTKh in visit updated.

**Comment by cyrush** [comment]
@jameskress  -- yes starting to take a look at issues now. I'll ping for help after some digging.

**Comment by jameskress** [comment]
@cyrush Great! I just built VisIt with the VTK-m RC and this branch of VTK-h. I had to remove an include from vtkh.cpp, but other than that it build and seemed to run correctly.

**Comment by cyrush** [comment]
@jameskress  -- is this the header issue you saw (missing `vtkmoptionparser/optionparser.h`)

```
vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/build.make:257: recipe for target 'vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/vtkmVectorMagnitude.cpp.o' failed
make[2]: *** [vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/vtkmVectorMagnitude.cpp.o] Error 1
In file included from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/OptionParserArguments.h:14:0,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/RuntimeDeviceConfigurationOptions.h:15,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/RuntimeDeviceConfiguration.h:16,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/RuntimeDeviceInformation.h:15,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/RuntimeDeviceTracker.h:18,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/ArrayHandleTransform.h:17,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/ArrayHandleCast.h:13,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/CoordinateSystem.h:16,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/DataSet.h:16,
                 from /vtk-h/src/vtkh/vtkm_filters/vtkmExtractStructured.hpp:5,
                 from /vtk-h/src/vtkh/vtkm_filters/vtkmExtractStructured.cpp:1:
/vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/OptionParser.h:45:10: fatal error: vtkmoptionparser/optionparser.h: No such file or directory
 #include <vtkmoptionparser/optionparser.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/build.make:117: recipe for target 'vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/vtkmClipWithField.cpp.o' failed
make[2]: *** [vtkh/vtkm_filters/CMakeFiles/vtkm_compiled_filters.dir/vtkmClipWithField.cpp.o] Error 1
In file included from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/OptionParserArguments.h:14:0,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/RuntimeDeviceConfigurationOptions.h:15,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/RuntimeDeviceConfiguration.h:16,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/RuntimeDeviceInformation.h:15,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/RuntimeDeviceTracker.h:18,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/ArrayHandleTransform.h:17,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/ArrayHandleCast.h:13,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/CoordinateSystem.h:16,
                 from /vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/DataSet.h:16,
                 from /vtk-h/src/vtkh/vtkm_filters/vtkmMarchingCubes.hpp:4,
                 from /vtk-h/src/vtkh/vtkm_filters/vtkmMarchingCubes.cpp:1:
/vtk-h/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/vtk-m-1.7.0-t5edp3vsr3xbu5o6ey5cegqscdlcmduv/include/vtkm-1.7/vtkm/cont/internal/OptionParser.h:45:10: fatal error: vtkmoptionparser/optionparser.h: No such file or directory
 #include <vtkmoptionparser/optionparser.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by jameskress** [comment]
@cyrush No, my issue was that I had to remove "#include <vtkm/cont/DeviceAdapterListTag.h>" from vtkh.cpp. It was bringing in deprecated stuff, and seems fine without it being there. 

I have however seen your issue quite often. I fix it by modifying the include path in the vtkm header file "vtkm/cont/internal/OptionParser.h". I am not a cmake wizard, so have always assumed that the path could be fixed by giving  the cmake files more "smarts", but I could be wrong. We may need to actually do an MR with vtkm and have the header path permanently changed. Any ideas on if CMake can do this for us, or does vtkm need to change?

This is the change I usually do:
---------------------- vtkm/cont/internal/OptionParser.h ----------------------
index 2e0d6127d..fd5b7e72d 100644
@@ -42,7 +42,7 @@ namespace internal
 
 // Include from third party.
 // @cond NONE
-#include <vtkmoptionparser/optionparser.h>
+#include <vtkm/thirdparty/optionparser/vtkmoptionparser/optionparser.h>
 // @endcond
 
 // Now restore the header guards as before so that other includes of (possibly different versions

------------------------

**Comment by cyrush** [comment]
thanks @jameskress  -- it does seem like vtk-m should be changed to use a path consistent with their install. I'll try a patch and see how that goes.

**Comment by cyrush** [comment]
Made some progress (compiling and linking!), but now all of my unit tests are segfaulting.

I had to do something different with fpic, however not sure that would cause such a drastic change.

**Comment by jameskress** [comment]
@cyrush I can confirm the seg faults as well. For me there was an issue with vtkh not knowing the path at runtime to the vtkm lib dir, but after exporting that I got the seg faults. 

I am a bit lost also as to what has changed so much that this is happening. May have something to do with that deprecated header, as that is the most substantive change. I'll look into that and see if I can find anything else.

**Comment by cyrush** [comment]
thanks @jameskress  I will be able to look at this again on Friday. 

The `t_vtkm_smoke` test runs at least partially and I haven't looked at the output from other unit tests, but I wonder if this a crash-on-exit style of mystery.

**Comment by jameskress** [comment]
@cyrush No worries! I will see if I can find out more today. So far I have the smoke test passing but test 5 (dataset) is failing in a getglobalbounds call. Plus most of the others are also failing, aside from threshold and the parallel smoke test. 

Update: I did a fresh checkout and install of this branch and the RC branch from vtkm. Now all of the tests are pasing except for 4 (t_vtk-h_empty_data, t_vtk-h_iso_volume, t_vtk-h_marching_cubes, t_vtk-h_point_renderer)

I don't know what was different between the two checkouts, but these 4 seem to be failing due to the same assertion:
t_vtk-h_iso_volume: /home/jkress/Downloads/vtk-m/vtkm/rendering/Camera.cxx:279: void vtkm::rendering::Camera::ResetToBounds(const vtkm::Bounds&, vtkm::Float64, vtkm::Float64, vtkm::Float64): Assertion `saveMode != MODE_3D' failed.

**Comment by jameskress** [comment]
@cyrush With the fresh checkouts and builds plus the camera fix that Ken has done, all of my unit tests are now passing. 

https://gitlab.kitware.com/vtk/vtk-m/-/merge_requests/2621#diff-content-2e4cef6e1dc8cfdafbba4d6d9dcee9148ab4c98b

**Comment by cyrush** [comment]
@jameskress  Q: were you doing static libs or shared libs for VTK-h?

**Comment by cyrush** [comment]
For me, using OpenMP with threads greater than 1, yields a seg fault. 

Looking at the most basic test (our vtk-m smoke test):

### vtk-m smoke test

#### default omp threads

```
Starting program: /vtk-h/build-debug/tests/thirdparty/t_vtkm_smoke 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running main() from /vtk-h/src/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from vtkm_smoke
[ RUN      ] vtkm_smoke.headers_work
[       OK ] vtkm_smoke.headers_work (0 ms)
[ RUN      ] vtkm_smoke.basic_use_serial
0 1 0 1 0 1
[       OK ] vtkm_smoke.basic_use_serial (1 ms)
[ RUN      ] vtkm_smoke.basic_use_openmp
[New Thread 0x7f3d68262700 (LWP 14805)]
[New Thread 0x7f3d67a61700 (LWP 14806)]
[New Thread 0x7f3d67260700 (LWP 14807)]
[New Thread 0x7f3d66a5f700 (LWP 14808)]
[New Thread 0x7f3d6625e700 (LWP 14809)]
[New Thread 0x7f3d65a5d700 (LWP 14810)]
[New Thread 0x7f3d6525c700 (LWP 14811)]
[New Thread 0x7f3d64a5b700 (LWP 14812)]
[New Thread 0x7f3d6425a700 (LWP 14813)]
[New Thread 0x7f3d63a59700 (LWP 14814)]
[New Thread 0x7f3d63258700 (LWP 14815)]
[New Thread 0x7f3d62a57700 (LWP 14816)]
[New Thread 0x7f3d62256700 (LWP 14817)]
[New Thread 0x7f3d61a55700 (LWP 14818)]
[New Thread 0x7f3d61254700 (LWP 14819)]
[New Thread 0x7f3d60a53700 (LWP 14820)]
[New Thread 0x7f3d60252700 (LWP 14821)]
[New Thread 0x7f3d5fa51700 (LWP 14822)]
[New Thread 0x7f3d5f250700 (LWP 14823)]
[New Thread 0x7f3d5ea4f700 (LWP 14825)]
[New Thread 0x7f3d5e24e700 (LWP 14826)]
[New Thread 0x7f3d5da4d700 (LWP 14829)]
[New Thread 0x7f3d5d24c700 (LWP 14830)]

Thread 3 "t_vtkm_smoke" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f3d67a61700 (LWP 14806)]
0x0000000000000000 in ?? ()
(gdb) 
```
### OMP_NUM_THREADS=1
```
root@3410fb22647a:/vtk-h/build-debug# env OMP_NUM_THREADS=1 ./tests/thirdparty/t_vtkm_smoke 
Running main() from /vtk-h/src/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from vtkm_smoke
[ RUN      ] vtkm_smoke.headers_work
[       OK ] vtkm_smoke.headers_work (0 ms)
[ RUN      ] vtkm_smoke.basic_use_serial
0 1 0 1 0 1
[       OK ] vtkm_smoke.basic_use_serial (0 ms)
[ RUN      ] vtkm_smoke.basic_use_openmp
0 1 0 1 0 1
[       OK ] vtkm_smoke.basic_use_openmp (0 ms)
[----------] 3 tests from vtkm_smoke (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 3 tests.
```

### OMP_NUM_THREADS=8
```
root@3410fb22647a:/vtk-h/build-debug# env OMP_NUM_THREADS=8 ./tests/thirdparty/t_vtkm_smoke 
Running main() from /vtk-h/src/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest_main.cc
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from vtkm_smoke
[ RUN      ] vtkm_smoke.headers_work
[       OK ] vtkm_smoke.headers_work (0 ms)
[ RUN      ] vtkm_smoke.basic_use_serial
0 1 0 1 0 1
[       OK ] vtkm_smoke.basic_use_serial (0 ms)
[ RUN      ] vtkm_smoke.basic_use_openmp
Segmentation fault
```

### Looking all of the vtk-h tests:

####  OMP_NUM_THREADS=1  (OK)
```
root@3410fb22647a:/vtk-h/build-debug# env OMP_NUM_THREADS=1 make test                       
Running tests...
Test project /vtk-h/build-debug
      Start  1: blt_gtest_smoke
 1/39 Test  #1: blt_gtest_smoke ..................   Passed    0.00 sec
      Start  2: blt_openmp_smoke
 2/39 Test  #2: blt_openmp_smoke .................   Passed    0.00 sec
      Start  3: blt_mpi_smoke
 3/39 Test  #3: blt_mpi_smoke ....................   Passed    0.01 sec
      Start  4: t_vtkm_smoke
 4/39 Test  #4: t_vtkm_smoke .....................   Passed    0.00 sec
      Start  5: t_vtk-h_smoke
 5/39 Test  #5: t_vtk-h_smoke ....................   Passed    0.00 sec
      Start  6: t_vtk-h_dataset
 6/39 Test  #6: t_vtk-h_dataset ..................   Passed    0.39 sec
      Start  7: t_vtk-h_clip
 7/39 Test  #7: t_vtk-h_clip .....................   Passed    0.83 sec
      Start  8: t_vtk-h_clip_field
 8/39 Test  #8: t_vtk-h_clip_field ...............   Passed    0.45 sec
      Start  9: t_vtk-h_vector_ops
 9/39 Test  #9: t_vtk-h_vector_ops ...............   Passed    2.30 sec
      Start 10: t_vtk-h_device_control
10/39 Test #10: t_vtk-h_device_control ...........   Passed    1.41 sec
      Start 11: t_vtk-h_empty_data
11/39 Test #11: t_vtk-h_empty_data ...............   Passed    0.14 sec
      Start 12: t_vtk-h_gradient
12/39 Test #12: t_vtk-h_gradient .................   Passed    1.41 sec
      Start 13: t_vtk-h_ghost_stripper
13/39 Test #13: t_vtk-h_ghost_stripper ...........   Passed    0.27 sec
      Start 14: t_vtk-h_iso_volume
14/39 Test #14: t_vtk-h_iso_volume ...............   Passed    0.40 sec
      Start 15: t_vtk-h_no_op
15/39 Test #15: t_vtk-h_no_op ....................   Passed    0.67 sec
      Start 16: t_vtk-h_marching_cubes
16/39 Test #16: t_vtk-h_marching_cubes ...........   Passed    1.70 sec
      Start 17: t_vtk-h_lagrangian
17/39 Test #17: t_vtk-h_lagrangian ...............   Passed    0.54 sec
      Start 18: t_vtk-h_log
18/39 Test #18: t_vtk-h_log ......................   Passed    0.75 sec
      Start 19: t_vtk-h_threshold
19/39 Test #19: t_vtk-h_threshold ................   Passed    0.67 sec
      Start 20: t_vtk-h_point_transform
20/39 Test #20: t_vtk-h_point_transform ..........   Passed    1.54 sec
      Start 21: t_vtk-h_mesh_renderer
21/39 Test #21: t_vtk-h_mesh_renderer ............   Passed    0.40 sec
      Start 22: t_vtk-h_multi_render
22/39 Test #22: t_vtk-h_multi_render .............   Passed   10.33 sec
      Start 23: t_vtk-h_point_renderer
23/39 Test #23: t_vtk-h_point_renderer ...........   Passed    0.61 sec
      Start 24: t_vtk-h_raytracer
24/39 Test #24: t_vtk-h_raytracer ................   Passed    0.72 sec
      Start 25: t_vtk-h_render
25/39 Test #25: t_vtk-h_render ...................   Passed    4.20 sec
      Start 26: t_vtk-h_slice
26/39 Test #26: t_vtk-h_slice ....................   Passed    0.43 sec
      Start 27: t_vtk-h_volume_renderer
27/39 Test #27: t_vtk-h_volume_renderer ..........   Passed    2.61 sec
      Start 28: t_vtk-h_smoke_par
28/39 Test #28: t_vtk-h_smoke_par ................   Passed    0.01 sec
      Start 29: t_vtk-h_dataset_par
29/39 Test #29: t_vtk-h_dataset_par ..............   Passed    1.55 sec
      Start 30: t_vtk-h_no_op_par
30/39 Test #30: t_vtk-h_no_op_par ................   Passed    2.35 sec
      Start 31: t_vtk-h_histogram_par
31/39 Test #31: t_vtk-h_histogram_par ............   Passed    1.70 sec
      Start 32: t_vtk-h_statistics_par
32/39 Test #32: t_vtk-h_statistics_par ...........   Passed    2.13 sec
      Start 33: t_vtk-h_marching_cubes_par
33/39 Test #33: t_vtk-h_marching_cubes_par .......   Passed    1.72 sec
      Start 34: t_vtk-h_multi_render_par
34/39 Test #34: t_vtk-h_multi_render_par .........   Passed    6.92 sec
      Start 35: t_vtk-h_particle_advection_par
35/39 Test #35: t_vtk-h_particle_advection_par ...   Passed    0.28 sec
      Start 36: t_vtk-h_scalar_renderer_par
36/39 Test #36: t_vtk-h_scalar_renderer_par ......   Passed    3.95 sec
      Start 37: t_vtk-h_raytracer_par
37/39 Test #37: t_vtk-h_raytracer_par ............   Passed    2.43 sec
      Start 38: t_vtk-h_sampling_par
38/39 Test #38: t_vtk-h_sampling_par .............   Passed    6.88 sec
      Start 39: t_vtk-h_volume_renderer_par
39/39 Test #39: t_vtk-h_volume_renderer_par ......   Passed    7.23 sec

100% tests passed, 0 tests failed out of 39

Total Test time (real) =  69.93 sec
```

###  OMP_NUM_THREADS=2 (most tests fail)
```
23% tests passed, 30 tests failed out of 39

Total Test time (real) =  25.66 sec

The following tests FAILED:
          4 - t_vtkm_smoke (SEGFAULT)
          6 - t_vtk-h_dataset (SEGFAULT)
          7 - t_vtk-h_clip (SEGFAULT)
          8 - t_vtk-h_clip_field (Subprocess aborted)
          9 - t_vtk-h_vector_ops (Subprocess aborted)
         10 - t_vtk-h_device_control (Subprocess aborted)
         12 - t_vtk-h_gradient (Subprocess aborted)
         13 - t_vtk-h_ghost_stripper (SEGFAULT)
         14 - t_vtk-h_iso_volume (Subprocess aborted)
         15 - t_vtk-h_no_op (SEGFAULT)
         16 - t_vtk-h_marching_cubes (Subprocess aborted)
         17 - t_vtk-h_lagrangian (SEGFAULT)
         18 - t_vtk-h_log (Subprocess aborted)
         20 - t_vtk-h_point_transform (Subprocess aborted)
         21 - t_vtk-h_mesh_renderer (SEGFAULT)
         22 - t_vtk-h_multi_render (Subprocess aborted)
         23 - t_vtk-h_point_renderer (SEGFAULT)
         24 - t_vtk-h_raytracer (SEGFAULT)
         25 - t_vtk-h_render (SEGFAULT)
         26 - t_vtk-h_slice (Subprocess aborted)
         27 - t_vtk-h_volume_renderer (Subprocess aborted)
         29 - t_vtk-h_dataset_par (Failed)
         30 - t_vtk-h_no_op_par (Failed)
         33 - t_vtk-h_marching_cubes_par (Failed)
         34 - t_vtk-h_multi_render_par (Failed)
         35 - t_vtk-h_particle_advection_par (Failed)
         36 - t_vtk-h_scalar_renderer_par (Failed)
         37 - t_vtk-h_raytracer_par (Failed)
         38 - t_vtk-h_sampling_par (Failed)
         39 - t_vtk-h_volume_renderer_par (Failed)
Errors while running CTest
```

**Comment by jameskress** [comment]
> @jameskress Q: were you doing static libs or shared libs for VTK-h?

@cyrush  I have been building with shared libs. It has been a while also since I have been able to use openmp due to downstream codes I have been working with. Compiling with openmp and static libs gives me what appear to be SOME of the same problems you are seeing. I am able to get test 5 to pass just fine, but most other tests after that failed


The following tests FAILED:
	  6 - t_vtk-h_dataset (SEGFAULT)
	  7 - t_vtk-h_clip (SEGFAULT)
	  8 - t_vtk-h_clip_field (Child aborted)
	  9 - t_vtk-h_vector_ops (Child aborted)
	 10 - t_vtk-h_device_control (Child aborted)
	 12 - t_vtk-h_gradient (Child aborted)
	 13 - t_vtk-h_ghost_stripper (Child aborted)
	 14 - t_vtk-h_iso_volume (Child aborted)
	 15 - t_vtk-h_no_op (Child aborted)
	 16 - t_vtk-h_marching_cubes (Child aborted)
	 17 - t_vtk-h_lagrangian (Child aborted)
	 18 - t_vtk-h_log (Child aborted)
	 20 - t_vtk-h_point_transform (Child aborted)
	 21 - t_vtk-h_mesh_renderer (SEGFAULT)
	 22 - t_vtk-h_multi_render (Child aborted)
	 23 - t_vtk-h_point_renderer (Child aborted)
	 24 - t_vtk-h_raytracer (SEGFAULT)
	 25 - t_vtk-h_render (SEGFAULT)
	 26 - t_vtk-h_slice (Child aborted)
	 27 - t_vtk-h_volume_renderer (Child aborted)
	 29 - t_vtk-h_dataset_par (Failed)
	 30 - t_vtk-h_no_op_par (Failed)
	 33 - t_vtk-h_marching_cubes_par (Timeout)
	 34 - t_vtk-h_multi_render_par (Timeout)
	 35 - t_vtk-h_particle_advection_par (Failed)
	 36 - t_vtk-h_scalar_renderer_par (Failed)
	 37 - t_vtk-h_raytracer_par (Failed)
	 38 - t_vtk-h_sampling_par (Failed)
	 39 - t_vtk-h_volume_renderer_par (Failed)
Errors while running CTest

**Comment by cyrush** [comment]
@goodbadwolf This is the branch we are using to update, so if you can get the changes here (let me know if you need perms, etc) that will make it easiest to check them

**Comment by goodbadwolf** [comment]
> @goodbadwolf This is the branch we are using to update, so if you can get the changes here (let me know if you need perms, etc) that will make it easiest to check them

@cyrush It took me longer to get a working build of vtk-h than expected. I have the changes that should fix the issue, but I do not have the perms to push it to this branch.

Preview of the fix:

**Comment by cyrush** [comment]
@goodbadwolf -- thanks for the update!

You should have permissions now, so try to push and let me know if there are problems.

**Comment by goodbadwolf** [comment]
@cyrush - Done

**Comment by cyrush** [comment]
thanks @goodbadwolf  -- I tested in ascent and things look good!

**Pull request merged**
