### PR TITLE
New new new vtkm

### PR DESCRIPTION
**Pull request by mclarsen**

### CODE REVIEW

**Comment by mclarsen** [comment]
The vtkm cuda linking warnings have not gone away, but it works.

**Comment by mclarsen** [comment]
@cyrush Does this docker error look like anything to you?

**Comment by cyrush** [comment]
looks like an issue with the spack config used in docker:

==> cmake@3.14.5 : externally installed in /Users/larsen30/cmake-v3.14.5

but I am confused where that is coming from, we aren't passing any spack_config_dir to uberenv in the docker build?

**Comment by mclarsen** [comment]
This is what happens when I make inadvertent changes to the spack branch.

**Review by cyrush — APPROVED** [review]

**Pull request merged**
