### PR TITLE
add uberenv, travis testing, and use shell closer to ascent to start

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
@mclarsen  @utkarshayachit   I added travis testing, and automated builds of vtk-h's deps.

I also took a pass at changes from utkarsh's reorg branch to resolve the tbb issues. 

The setup looks a bit more like how vtk-h was being built in ascent before the split, but that doesn't mean we can't evolve to something else longer term.

**Comment by cyrush** [comment]
thought icet was still being used, but maybe thats not the case?

**Comment by cyrush** [comment]
on this branch, vtk-h stand alone w/ all tpls (excluding cuda) is building and passing tests.

**Comment by utkarshayachit** [comment]
I suspect all that we needed to do was make the TBB link public. I didn't want to make it public by default, unless I understood why it needed to be public. How attached are you to the `blt_add_library` changes? I'd vote for experimenting with direct calls to `target_link_libraries` and `target_include_directories` rather than public linking and project wide `include_directories`. thoughts?

**Comment by cyrush** [comment]
@utkarshayachit, let me hack at it a bit more, there is still an issue with using vtk-h in ascent related to tbb. 

I am on board with moving away from project wide includes + moving to not using public linkage where possible -- but it would be nice to do so w/o lots of copy and paste boilerplate per target, too easy to make a typo. 

Also, I know the CI stuff is frustrating, but thats the closest proxy we have for automated testing of the full build w/ tpls on our HPC systems.  So I want to get all of that as healthy as possible, then we can vet further changes with the CI. 

I should have some time to work on this today.

**Comment by utkarshayachit** [comment]
> but it would be nice to do so w/o lots of copy and paste boilerplate per target, 

agreed. Given that vtk-h is still tiny, I didn't want to commit to a macro too early in the lifecycle.

**Comment by mclarsen** [comment]
I think that TBB will have to be public. The way vtkm is including files, just including vtkm::cont::DataSet pulls in code that requires having the tbb headers, so at least ascent will need it.

**Comment by mclarsen** [comment]
Also, does it make sense to include vtkm as a submodule, since it is required to build vtkh? I know that people may have a separate installation they use in multiple places. I am asking because I am writing the build documentation for ascent. Perhaps I will just write as it works now and not as a submodule.

**Comment by utkarshayachit** [comment]
> vtkm as a submodule, since it is required to build vtkh

yes indeed. but let's wait on that till things mature a little. For if you think how this will end up in VTK (and then ParaView) , it will be long chain of nested submodules and we need to make sure we handle the dev workflow/testing complications it brings gracefully.

> Perhaps I will just write as it works now and not as a submodule.

that get's my vote.

**Comment by mclarsen** [comment]
Ok, I will go that route.

**Comment by cyrush** [comment]
@utkarshayachit @mclarsen , the rpath issue appears to be an issue with how spack is building either vtkm or vtkh, should have a fix soon.

**Comment by cyrush** [comment]
@utkarshayachit  @mclarsen 

ok, i think i worked everything out -- lets see how the test go

**Comment by utkarshayachit** [comment]
I am fine with this change for now. But are you okay with me bringing back the target libraries cmake code one this is merged in? I think we should stay away from global includes (as in `SystemInclude.cmake`), and distinguish between PRIVATE and PUBLIC library links right from the start as that'll come to bite us later. Plus the tbb issue was unrelated, so no reason to not use the target libraries approach at this point.

**Comment by cyrush** [comment]
@utkarshayachit  here is all that is left in ` SetupIncludes.cmake`

```
################################
#  Project Wide Includes
################################
# so we can see use "vtkh/zzz.hxx"
include_directories(${PROJECT_SOURCE_DIR})
# add lodepng include dir
include_directories(${PROJECT_SOURCE_DIR}/vtkh/thirdparty_builtin/lodepng)
# add DIY include dir
include_directories(${PROJECT_SOURCE_DIR}/vtk.thirdparty_builtin/diy/include)
```

Nothing related to vtkm or tbb anymore  -- those didn't need to be there, they were leftovers from before we where using BLT.

BLT is using `target_include_directories` and  `target_link_directories` for things passed via DEPENDS_ON. By default, BLT uses PUBLIC - which I think is what we need for our current case.  

One thing it doesn't do yet is differentiate between the build and install interfaces for includes. 

In the future, BLT will also allow us to select INTERFACE, or PRIVATE and do the right thing.

For vtk-h's potential PRIVATE cases (like `lodepng` since it shouldn't be needed the interface?) can't we simply use object libraries? It seems better than building another lib & the includes don't need to propagate outside of the build system, so `include_directories()` at some sensible scope won't undermine us. 


There is nothing magic about the BLT targets, so we could use statements like these with the BLT targets:

```
  target_include_directories(vtkh_filters_par
    PUBLIC
      $<BUILD_INTERFACE:${VTKh_SOURCE_DIR}>
      $<BUILD_INTERFACE:${VTKh_BINARY_DIR}>
      $<INSTALL_INTERFACE:${VTKh_INSTALL_INCLUDE_DIR}>
    )
```
Do we think DIY will be PRIVATE or INTERFACE? 

If INTERFACE you could also include DIY as an INTERFACE dep with standard CMake. 

That said -- we really haven't tested CUDA support after this refactor. BLT smooths out a bunch of issues there (b/c of how FindCUDA works). 

Basically, you can't use much, if any cmake target settings for CUDA targets after they are created via FindCUDA magic. So you have to do monkey business with global settings for CUDA. I know newer CMake's have built in support for CUDA, but it seems many kinks are still being worked out.

We can migrate to wield CMake differently -- but it would be nice to have active CUDA testing before we poke too much more. 

I understand you may want to remove BLT longer term &  I know you have an eye for what will work well in VTK proper and  ParaView -- I trust you have a very clear idea of will be necessary. Honestly, I think BLT gives us a good insulation layer to avoid lots of extra CMake and some future proofing. I don't see it undermining us right now. 


Note: I haven't tested CUDA (including the spack build paths), but I can do that on my mac & I will.

**Comment by utkarshayachit** [comment]
Let's get this merged.

BTW I had tested my original changes with CUDA enabled on link. All  cuda tests had passed. Also, cuda-lang support in CMake 3.9 should simplify FindCUDA magic. My concern with blt is that it adds an unnecessary obfuscation to code -- for a "tiny" vtk-h library, how much cmake magic do we really need? and if we do, we have other issue :).

**Comment by cyrush** [comment]
I do hope that CMake 3.9 helps with the CUDA support.  Do you know if it supports cuda-clang?

Maybe we can discuss the BLT in more detail in the future. My position is that it helps us write much less CMake code now, and still helps us use CMake well. If VTK-h is pulled into something else (or maybe adopts VTH-m's CMake infrastructure) it may not be necessary in the future.  

To give you some context,  BLT is being used across several projects, its entire goal is to make it much easer to get up and running with CMake + common tools (gtest, etc). It's starting to help us turn tide and greatly increase with CMake adoption at LLNL.

**Comment by cyrush** [comment]
(testing cuda now)

**Comment by cyrush** [comment]
I am going to have to try on a different platform, VTK-m is yelling at me about C++11 support on my MAC. 

```
In file included from /Users/harrison37/Work/vtk-h/src/vtkh/filters/WaveletCompressor.cpp:1:
In file included from /Users/harrison37/Work/vtk-h/src/vtkh/filters/WaveletCompressor.hpp:5:
In file included from /Users/harrison37/Work/vtk-h/src/vtkh/filters/Filter.hpp:5:
In file included from /Users/harrison37/Work/vtk-h/src/vtkh/DataSet.hpp:9:
In file included from /Users/harrison37/Work/vtk-h/uberenv_libs/spack/opt/spack/darwin-x86_64/clang-3.4svn/vtkm-kitware-gitlab-4ekipjh5pj54ods6oslwwv2pzosa7i5b/include/vtkm/cont/DataSet.h:23:
In file included from /Users/harrison37/Work/vtk-h/uberenv_libs/spack/opt/spack/darwin-x86_64/clang-3.4svn/vtkm-kitware-gitlab-4ekipjh5pj54ods6oslwwv2pzosa7i5b/include/vtkm/cont/ArrayHandle.h:25:
In file included from /Users/harrison37/Work/vtk-h/uberenv_libs/spack/opt/spack/darwin-x86_64/clang-3.4svn/vtkm-kitware-gitlab-4ekipjh5pj54ods6oslwwv2pzosa7i5b/include/vtkm/Assert.h:24:
/Users/harrison37/Work/vtk-h/uberenv_libs/spack/opt/spack/darwin-x86_64/clang-3.4svn/vtkm-kitware-gitlab-4ekipjh5pj54ods6oslwwv2pzosa7i5b/include/vtkm/internal/Configure.h:271:2: error: "VTK-m requires at least a C++11 compiler"
#error "VTK-m requires at least a C++11 compiler"
```

**Comment by cyrush** [comment]
@utkarshayachit, even if you compiled your branch CUDA w/ on, i suspect the vtk-h filters themselves were not being compiled with nvcc. (which we need)

`add_library(vtkh_filters ${Sources} ${Headers})` would not have triggered nvcc compile.

The issue on my machine looks like I need to pass c++11 flags to CUDA, i'll try to tackle soon.

**Comment by cyrush** [comment]
Working on testing, my goal is to merge tonight.

**Comment by cyrush** [comment]
still getting c++11 errors on different platform, so the flags issue isn't just on my OSX machine.

**Comment by mclarsen** [comment]
It worked previously on surface. Maybe checkout the current develop and look at the flags that are passed.

**Comment by cyrush** [comment]
Found the issue. 

c++11 was set for the first pair of cuda enabled libs (vtkh_core and vtkh_core_par), but not filtering + rendering -- turns out I had a dumb typo with my push/pop of nvcc flags that was clearing them:

I was setting `CUDA_NVCC_FLAGS` back to `CUDA_NVCC_FLAGS_PREVIOUS`, but the cmake var I was using was actually named `CUDA_NVCC_FLAGS_PREV` --- so the were getting cleared after setting up vtk_core_par.

We only had one lib before, so this typo didn't bite us in ascent. 

Sorry it took so long to resolve, didn't have a window of time to focus on this during normal hours. 

I am finishing a compile now. Compiles of VTK-h w/ CUDA on take quite while -- 30+ minutes, we need to find some ways to tame VTK-m to get compile times down.

**Comment by cyrush** [comment]
Built w/ cuda + tests passed. 

Merging into @utkarshayachit's `reorg` branch, which I think will be ready to merge into `master`.

Updated the ascent `task/move_vtk-h_out ` to again use the vtk-h `reorg` branch.

Quite concerned about the vtk-m compile times, it would be nice to get to the bottom of that very soon. Also, release build w/o debug symbols generates a pretty large `so` for just a handful of filters:

```
surface86@cyrush:du -ch lib/libvtkh_filters.so 
186M	lib/libvtkh_filters.so
186M	total
surface86@cyrush:objdump --syms lib/libvtkh_filters.so  | grep debug
(empty)
```

The problem seems to be isolated to filters -- the  largest other lib is rendering par which is  ~30mb.

**Comment by mclarsen** [comment]
I am also concerned about the compile times. I mentioned it on the vtkm call. By far the longest filter compile time is marching cubes. I asked Robert if he had experienced the same and he reported time compile time for that filer as 2ish minutes which is a far cry from the 20+ minutes. We must be doing something different.

**Pull request merged**
