### PR TITLE
Parallel contour tree

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
if you use vtk-m with MPI enable, this will go away.

**Comment by danlipsa** [comment]
Rebased on the SHA needed by ascent.

**Comment by mclarsen** [comment]
Are you passing the MPI_Comm to vtkm or is it using world?

**Comment by danlipsa** [comment]
Yes, I am passing what I receive from vtkh:
https://github.com/Alpine-DAV/vtk-h/pull/130/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.hpp#diff-1d0961a081b8d0855e7f75d57bd1c0eaR95

**Comment by mclarsen** [comment]
Closing as this work was merge in another PR

**Pull request closed without merging**
