### PR TITLE
Enable building shared libs with CUDA with VTKm >= 1.7

### PR DESCRIPTION
**Pull request by kwryankrattiger**
@cyrush @mclarsen 

This seems to be working for me, I ran the tests building shared and static libs and both have same results. ref. #236

### CODE REVIEW

**Comment by kwryankrattiger** [comment]
note: many of the tests fail using develop. I am not sure if this is a known issue or not. All of the smoke tests pass.

```
          8 - t_vtkm_smoke (Not Run)
         10 - t_vtk-h_dataset (Failed)
         11 - t_vtk-h_clip (Failed)
         12 - t_vtk-h_clip_field (Failed)
         13 - t_vtk-h_vector_ops (Failed)
         14 - t_vtk-h_device_control (Failed)
         15 - t_vtk-h_empty_data (Failed)
         16 - t_vtk-h_gradient (Failed)
         17 - t_vtk-h_ghost_stripper (Not Run)
         18 - t_vtk-h_iso_volume (Not Run)
         19 - t_vtk-h_no_op (Not Run)
         20 - t_vtk-h_marching_cubes (Not Run)
         21 - t_vtk-h_lagrangian (Not Run)
         22 - t_vtk-h_log (Not Run)
         23 - t_vtk-h_threshold (Not Run)
         24 - t_vtk-h_point_transform (Not Run)
         25 - t_vtk-h_mesh_renderer (Not Run)
         26 - t_vtk-h_mesh_quality (Not Run)
         27 - t_vtk-h_multi_render (Not Run)
         28 - t_vtk-h_point_renderer (Not Run)
         29 - t_vtk-h_raytracer (Not Run)
         30 - t_vtk-h_render (Not Run)
         31 - t_vtk-h_slice (Not Run)
         32 - t_vtk-h_volume_renderer (Not Run)
         33 - t_vtk-h_cuda (Not Run)
         34 - t_vtk-h_smoke_par (Failed)
         35 - t_vtk-h_dataset_par (Failed)
         36 - t_vtk-h_no_op_par (Failed)
         37 - t_vtk-h_histogram_par (Failed)
         38 - t_vtk-h_statistics_par (Failed)
         39 - t_vtk-h_marching_cubes_par (Failed)
         40 - t_vtk-h_multi_render_par (Failed)
         41 - t_vtk-h_particle_advection_par (Failed)
         42 - t_vtk-h_scalar_renderer_par (Failed)
         43 - t_vtk-h_raytracer_par (Failed)
         44 - t_vtk-h_sampling_par (Failed)
         45 - t_vtk-h_volume_renderer_par (Failed)
```

**Comment by kwryankrattiger** [comment]
@mclarsen I tried adding a CI test here to make sure the CUDA +shared variant was working, but it doesn't seem like it wants to run. Not sure if the `azure-pipelines.yml` is protected on the azure service or not.

**Comment by mclarsen** [comment]
> @mclarsen I tried adding a CI test here to make sure the CUDA +shared variant was working, but it doesn't seem like it wants to run. Not sure if the `azure-pipelines.yml` is protected on the azure service or not.

It gets built with cuda, but it can't run because there is no GPU hardware provisioned.

**Comment by kwryankrattiger** [comment]
> there is no GPU hardware provisioned.

Oh yeah, duh, same on my test system :face_exhaling:

**Review by cyrush — APPROVED** [review]

**Comment by cyrush** [comment]
@kwryankrattiger thanks!

**Pull request merged**
