### PR TITLE
check for data earlier

### PR DESCRIPTION
**Pull request by nicolemarsaglia**

### CODE REVIEW

**Comment by nicolemarsaglia** [comment]
@cyrush I am getting this error on my checks:

##[warning]An image label with the label ubuntu-16.04 does not exist.
,##[error]The remote provider was unable to process the request.

After some googling it looks like Microsoft/AzureOps has stopped supporting Ubuntu-16.04.

**Comment by cyrush** [comment]
@nicolemarsaglia -- correct,  can you try merging develop into this branch to pick up new CI settings and see if that resolves?

**Comment by nicolemarsaglia** [comment]
I've pulled develop and merged that into my branch and it says it is all already up to date. Is there a different git command I should do?

**Comment by cyrush** [comment]
ahh, yes, I fixed this in https://github.com/Alpine-DAV/vtk-h/pull/229

But that's hasn't been merged yet. 

You can take the azure-pipelines.yml file from that branch

**Comment by nicolemarsaglia** [comment]
Sounds good, I'll do that! Thanks!

**Review by cyrush — APPROVED** [review]
Looks good!

**Pull request merged**
