### PR TITLE
PA fix

### PR DESCRIPTION
**Pull request by dpugmire**
This is a duplicate to PR 137, which is stale for some reason...
Fix for the issue that Matt was having with unstructured grids.

### CODE REVIEW

**Review by mclarsen — COMMENTED** [review]
This is kinda weird since it includes commits from over a year ago. Do you know why that is?

**Comment by dpugmire** [comment]
I have no idea how that happened.... The intent was refresh the ealier PR (from 2 Oct). I didn't realize that was never merged.

**Comment by mclarsen** [comment]
I think what happened is that you never created a new branch and its bringing in the older stuff. I don't see this as a real issue and I'll merge this when it passes.

**Comment by mclarsen** [comment]
If you do more work, branch off develop.

**Pull request merged**
