### PR TITLE
Kokkos build

### PR DESCRIPTION
**Pull request by nicolemarsaglia**
VTK-h Kokkos depends on VTK-m being built with Kokkos. 

Set up Kokkos initialization for whether we have Kokkos_HIP or Kokkos_CUDA. This  may need tweaking as we start running experiments.

### CODE REVIEW

**Review by cyrush — APPROVED** [review]

**Comment by cyrush** [comment]
Looks good, one Q: Is this all with VTK-m 1.7.1?

**Comment by nicolemarsaglia** [comment]
Yes, it was.

**Comment by cyrush** [comment]
We may still need some logic guards related to kokkos here.

**Comment by cyrush** [comment]
we should add a kokkos + cuda spec case to https://github.com/Alpine-DAV/vtk-h/blob/develop/azure-pipelines.yml

**Comment by nicolemarsaglia** [comment]
> We may still need some logic guards related to kokkos here.

Totes. I'm missing a guard around the serial case.

**Comment by cyrush** [comment]
nice  -- back in working order, can we also add a kokkos case to the CI? 
Let me know if you want to talk through the process.

**Comment by nicolemarsaglia** [comment]
> nice -- back in working order, can we also add a kokkos case to the CI? Let me know if you want to talk through the process.

Yes, I would like a little coaching on that. I looked at the file and wasn't entirely sure what to do.

**Pull request merged**
